stages:
  - build
  - test
  - runEtl

image: triply/ci:20210723-2

default:
  before_script:
    # Gitlab registry
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

build-etl:
  stage: build
  script:
    - ./config/ci/build etl
  only:
    variables:
      - $MODE == null
build-rdf2edm:
  stage: build
  script:
    - ./config/ci/build rdf2edm
  only:
    variables:
      - $MODE == null

test-etl:
  stage: test
  script:
    - ./config/ci/test
  only:
    variables:
      - $MODE == null

runAcceptance:
  stage: runEtl
  script:
    - ./config/ci/run acceptance
  only:
    variables:
      - $MODE == "acceptance"
runProduction:
  stage: runEtl
  script:
    - ./config/ci/run production
  only:
    variables:
      - $MODE == "production"
