#!/bin/bash


echoinfo ${CI_COMMIT_MESSAGE} | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' && [ "${CI_COMMIT_REF_NAME}" = "master" ] && echo "Skipping version builds on the master branche to avoid the pipeline doing the same work twice" && exit;
source ./config/ci/.env
if [ -n "${FORCE}" ]; then
  DOCKER_ARG="--no-cache"
fi

now=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
echoinfo "Building for tag ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} at ${now}"
docker build \
    -f ./config/docker/Dockerfile \
    ${DOCKER_ARG} \
    --build-arg "NPM_TOKEN=${NPM_TOKEN}" \
    --build-arg "BUILD_REF=${CI_COMMIT_REF_NAME}" \
    --build-arg BUILD_DATE="${now}" \
    --build-arg "COMMIT_SHA=${CI_COMMIT_SHA}" \
    -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} \
    .
