#!/bin/bash

set -e
echo ${CI_COMMIT_MESSAGE} | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' && [ "${CI_COMMIT_REF_NAME}" = "master" ] && echo "Skipping version builds on the master branche to avoid the pipeline doing the same work twice" && exit;
source ./config/ci/.env

DOCKER_IMAGE_NAME+="-etl" # only testing the etl
now=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
echoinfo "Testing docker image ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} at ${now}"
docker run --rm ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} yarn run util:lint
docker run --rm ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} yarn run util:validateTs
