PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX dc:      <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX void:    <http://rdfs.org/ns/void#>
PREFIX schema:  <http://schema.org/>
PREFIX edm:     <http://www.europeana.eu/schemas/edm/>
PREFIX ore:     <http://www.openarchives.org/ore/terms/>

CONSTRUCT {
    ?uri_cho a edm:ProvidedCHO ;
         edm:type ?edm_type ;
         dc:creator ?creator ;
         dc:description ?description ;
         dc:type ?genre ;
         dc:subject ?subject ;
         dc:title ?name ;
         dcterms:alternative ?altName ;
         dc:publisher ?publisher ;
         owl:sameAs ?sameAs ;
         dcterms:spatial ?spatial ;
         dcterms:temporal ?temporal ;
         dcterms:medium ?material .   

    ?uri_ore a ore:Aggregation ;
         edm:aggregatedCHO ?uri_cho ;
         edm:provider ?provider ;
         edm:dataProvider ?dataProvider ;
         edm:rights ?license ;
         edm:isShownBy ?isShownBy ;
         edm:isShownAt ?isShownAt .

}
WHERE {
    ?uri_cho schema:mainEntityOfPage [schema:isPartOf <http://data.bibliotheken.nl/id/dataset/albac> ] .
    ?uri_cho a schema:Article  .
    BIND(("IMAGE") as ?edm_type) 

      # Generate an "URI_CHO#agg" URI pointing to a ore:Aggregation resource. 
      BIND( URI(CONCAT(STR(?uri_cho),"#agg")) as ?uri_ore)

      # NOTE: The VAR_PROVIDER will be replaced during runtime by the starter.sh script.
      # Europeana requires the provider value to be specified through the aggregation process.
      BIND( STR('KB') as ?provider)

      OPTIONAL { ?uri_cho schema:creator/schema:name ?creator }
      OPTIONAL { ?uri_cho schema:description ?description }
      OPTIONAL { ?uri_cho schema:genre ?genre }
      OPTIONAL { ?uri_cho schema:name ?name }
      OPTIONAL { ?uri_cho schema:image/schema:license ?license }
      OPTIONAL { ?uri_cho schema:publisher ?publisher }
      OPTIONAL { ?uri_cho schema:sameAs ?sameAs }
      OPTIONAL { ?uri_cho schema:locationCreated ?spatial }
      OPTIONAL { ?uri_cho schema:dateCreated ?temporal }
      OPTIONAL { ?uri_cho schema:material ?material }
      OPTIONAL {
        # Europeana requires valid URI for edm:isShownAt 
        ?uri_cho schema:url/schema:contentUrl ?url 
        BIND(IRI(?url) as ?isShownAt)  
      }
      OPTIONAL {
        # Europeana requires valid URI for edm:isShownBy 
        ?uri_cho schema:image/schema:contentUrl ?image
        BIND(IRI(?image) as ?isShownBy)
      }
}